<a href="https://colab.research.google.com/github/Soni-20/BACTERIAL-IMAGE-CLASSIFICATION/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/MyDrive/LSTM/

/content/drive/MyDrive/LSTM


In [4]:
!ls

ACINETOBACTER	      Lactobacillus.delbrueckii  Propionibacterium_acnes
Bacteroides.fragilis  Lactobacillus.jehnsenii	 Pseudomonas_aeruginosa
Bifidobacterium.spp   Lactobacillus.paracasei	 Staphylococcus_aureus
Candida.albicans      Lactobacillus.plantarum	 Staphylococcus_epidermidis
Fusobacterium	      Porfyromonas_gingivalis	 Staphylococcus_saprophiticus


In [6]:
DIRECTORY = ''

CATEGORIES = [ 'ACINETOBACTER',	      'Lactobacillus.delbrueckii',  'Propionibacterium_acnes',
'Bacteroides.fragilis'  ,'Lactobacillus.jehnsenii'	, 'Pseudomonas_aeruginosa',
'Bifidobacterium.spp'  , 'Lactobacillus.paracasei'	, 'Staphylococcus_aureus',
'Candida.albicans' ,     'Lactobacillus.plantarum',	 'Staphylococcus_epidermidis',
'Fusobacterium'	    ,  'Porfyromonas_gingivalis'	, 'Staphylococcus_saprophiticus']

In [7]:
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])

In [8]:
data

[[array([[212, 212, 211, ..., 205, 211, 210],
         [211, 212, 211, ..., 177, 210, 210],
         [211, 210, 210, ..., 196, 211, 209],
         ...,
         [159, 184, 190, ..., 168, 212, 213],
         [164, 182, 195, ..., 214, 212, 211],
         [217, 161, 178, ..., 187, 156, 211]], dtype=uint8),
  0],
 [array([[212, 212, 211, ..., 205, 211, 210],
         [211, 212, 211, ..., 177, 210, 210],
         [211, 210, 210, ..., 196, 211, 209],
         ...,
         [159, 184, 190, ..., 168, 212, 213],
         [164, 182, 195, ..., 214, 212, 211],
         [217, 161, 178, ..., 187, 156, 211]], dtype=uint8),
  0],
 [array([[211, 212, 209, ..., 210, 211, 202],
         [211, 212, 213, ..., 209, 210, 209],
         [212, 201, 212, ..., 210, 210, 211],
         ...,
         [213, 214, 220, ..., 214, 213, 214],
         [213, 214, 221, ..., 212, 213, 213],
         [213, 213, 196, ..., 212, 213, 213]], dtype=uint8),
  0],
 [array([[181, 214, 214, ..., 211, 212, 212],
         [215, 216, 2

In [9]:
data[0][1]

0

In [10]:

import random

random.shuffle(data)

In [11]:
X = []
y = []

In [12]:
for features, label in data:
    X.append(features)
    y.append(label)

In [13]:
X = np.array(X)
y = np.array(y)

In [14]:
X

array([[[208,  91,  89, ..., 208, 208, 208],
        [169, 145, 208, ..., 207, 207, 208],
        [190, 212, 209, ..., 209, 207, 208],
        ...,
        [101, 116, 214, ..., 176, 208, 211],
        [156, 110, 201, ..., 195, 211, 210],
        [175, 107, 176, ..., 187, 210, 210]],

       [[219, 219, 217, ..., 218, 219, 218],
        [219, 219, 218, ..., 219, 216, 218],
        [218, 218, 218, ..., 218, 216, 219],
        ...,
        [155, 197, 176, ..., 219, 219, 219],
        [211, 172, 204, ..., 218, 218, 218],
        [169, 221, 220, ..., 213, 217, 219]],

       [[159, 211, 212, ..., 147, 199, 218],
        [212, 198, 202, ..., 167, 172, 192],
        [212, 208, 207, ..., 136, 213, 219],
        ...,
        [218, 219, 219, ..., 222, 221, 220],
        [218, 217, 218, ..., 220, 221, 221],
        [217, 217, 217, ..., 220, 220, 220]],

       ...,

       [[212, 212, 211, ..., 205, 211, 210],
        [211, 212, 211, ..., 177, 210, 210],
        [211, 210, 210, ..., 196, 211, 209

In [15]:
y

array([ 8,  7,  1,  1,  6, 14,  2,  0,  7,  7,  6, 14,  2,  0,  1, 10,  4,
        1, 14,  6,  2,  1,  6,  2,  2, 14,  5,  0,  4, 14,  1,  3,  3, 11,
       10, 13,  8, 10,  4,  2,  0,  4,  7,  5, 14,  3, 14,  6,  5,  2,  3,
       14, 10,  8, 14, 10,  0,  8, 14,  5,  2,  6,  3,  6,  3,  7,  3, 10,
        7,  1,  9,  5, 14, 10,  3,  2,  3,  4,  5, 10,  4,  8, 14,  7,  3,
        2,  3,  4,  4,  6,  5,  6,  6,  7, 10,  1, 10,  1,  6,  7,  2,  0,
        9,  8,  6,  6,  8,  5, 14,  3,  7,  4,  7,  5,  0, 14,  1,  2,  1,
        1,  0,  8,  7,  5,  3, 14,  6, 10, 14,  0,  3,  8,  2,  0,  4,  3,
        0,  4,  1,  3,  4,  5,  4,  2, 10,  6,  8,  6,  0,  8,  8, 10,  4,
        0,  7,  1,  7,  5,  7,  6,  5,  8,  1,  2, 14,  3,  6, 13,  4,  8,
        4,  2,  1, 10,  2,  8,  6,  2,  1, 10,  1,  5,  1,  6,  6,  2, 10,
        6, 10, 10,  3,  4,  7,  3,  0,  5, 10,  8,  5,  8,  2,  0,  2,  0,
        3, 14, 14,  7,  5,  7,  5,  4, 11,  1,  0,  3,  3,  4,  2, 10,  0,
        4,  5,  7,  0,  8

In [16]:
import pickle

In [17]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))

In [18]:

X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [19]:
X

array([[[208,  91,  89, ..., 208, 208, 208],
        [169, 145, 208, ..., 207, 207, 208],
        [190, 212, 209, ..., 209, 207, 208],
        ...,
        [101, 116, 214, ..., 176, 208, 211],
        [156, 110, 201, ..., 195, 211, 210],
        [175, 107, 176, ..., 187, 210, 210]],

       [[219, 219, 217, ..., 218, 219, 218],
        [219, 219, 218, ..., 219, 216, 218],
        [218, 218, 218, ..., 218, 216, 219],
        ...,
        [155, 197, 176, ..., 219, 219, 219],
        [211, 172, 204, ..., 218, 218, 218],
        [169, 221, 220, ..., 213, 217, 219]],

       [[159, 211, 212, ..., 147, 199, 218],
        [212, 198, 202, ..., 167, 172, 192],
        [212, 208, 207, ..., 136, 213, 219],
        ...,
        [218, 219, 219, ..., 222, 221, 220],
        [218, 217, 218, ..., 220, 221, 221],
        [217, 217, 217, ..., 220, 220, 220]],

       ...,

       [[212, 212, 211, ..., 205, 211, 210],
        [211, 212, 211, ..., 177, 210, 210],
        [211, 210, 210, ..., 196, 211, 209

In [20]:
y

array([ 8,  7,  1,  1,  6, 14,  2,  0,  7,  7,  6, 14,  2,  0,  1, 10,  4,
        1, 14,  6,  2,  1,  6,  2,  2, 14,  5,  0,  4, 14,  1,  3,  3, 11,
       10, 13,  8, 10,  4,  2,  0,  4,  7,  5, 14,  3, 14,  6,  5,  2,  3,
       14, 10,  8, 14, 10,  0,  8, 14,  5,  2,  6,  3,  6,  3,  7,  3, 10,
        7,  1,  9,  5, 14, 10,  3,  2,  3,  4,  5, 10,  4,  8, 14,  7,  3,
        2,  3,  4,  4,  6,  5,  6,  6,  7, 10,  1, 10,  1,  6,  7,  2,  0,
        9,  8,  6,  6,  8,  5, 14,  3,  7,  4,  7,  5,  0, 14,  1,  2,  1,
        1,  0,  8,  7,  5,  3, 14,  6, 10, 14,  0,  3,  8,  2,  0,  4,  3,
        0,  4,  1,  3,  4,  5,  4,  2, 10,  6,  8,  6,  0,  8,  8, 10,  4,
        0,  7,  1,  7,  5,  7,  6,  5,  8,  1,  2, 14,  3,  6, 13,  4,  8,
        4,  2,  1, 10,  2,  8,  6,  2,  1, 10,  1,  5,  1,  6,  6,  2, 10,
        6, 10, 10,  3,  4,  7,  3,  0,  5, 10,  8,  5,  8,  2,  0,  2,  0,
        3, 14, 14,  7,  5,  7,  5,  4, 11,  1,  0,  3,  3,  4,  2, 10,  0,
        4,  5,  7,  0,  8

In [21]:
X = X/255
X

X = X.reshape(-1, 60, 60, 1)


In [22]:

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten


In [23]:
from keras.layers import LSTM

In [24]:
model = Sequential()
model.add(LSTM(60,activation='relu',kernel_initializer='he_uniform',input_shape=(60,60)))
model.add(Dense(60))
model.add(Dense(28, activation = 'softmax'))

In [25]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [27]:

model.fit(X, y, epochs=1008, validation_split=0.1)

Epoch 1/1008
7/7 [==============================] - 0s 45ms/step - loss: 0.8932 - accuracy: 0.6814 - val_loss: 1.7107 - val_accuracy: 0.3478
Epoch 2/1008
7/7 [==============================] - 0s 39ms/step - loss: 0.9085 - accuracy: 0.6765 - val_loss: 1.6505 - val_accuracy: 0.3478
Epoch 3/1008
7/7 [==============================] - 0s 38ms/step - loss: 0.8661 - accuracy: 0.7304 - val_loss: 1.9510 - val_accuracy: 0.3043
Epoch 4/1008
7/7 [==============================] - 0s 39ms/step - loss: 0.9338 - accuracy: 0.6716 - val_loss: 1.6813 - val_accuracy: 0.3913
Epoch 5/1008
7/7 [==============================] - 0s 44ms/step - loss: 0.9717 - accuracy: 0.6667 - val_loss: 1.7128 - val_accuracy: 0.3043
Epoch 6/1008
7/7 [==============================] - 0s 43ms/step - loss: 0.9724 - accuracy: 0.6373 - val_loss: 1.7068 - val_accuracy: 0.2609
Epoch 7/1008
7/7 [==============================] - 0s 37ms/step - loss: 0.9213 - accuracy: 0.6814 - val_loss: 1.9032 - val_accuracy: 0.3913
Epoch 8/1008


In [28]:
import cv2
import keras

In [29]:
import numpy as np

CATEGORIES = [ 'ACINETOBACTER',	      'Lactobacillus.delbrueckii',  'Propionibacterium_acnes',
'Bacteroides.fragilis'  ,'Lactobacillus.jehnsenii'	, 'Pseudomonas_aeruginosa',
'Bifidobacterium.spp'  , 'Lactobacillus.paracasei'	, 'Staphylococcus_aureus',
'Candida.albicans' ,     'Lactobacillus.plantarum',	 'Staphylococcus_epidermidis',
'Fusobacterium'	    ,  'Porfyromonas_gingivalis'	, 'Staphylococcus_saprophiticus']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr



In [30]:

prediction = model.predict([image('/content/drive/MyDrive/LSTM/Bacteroides.fragilis/Bacteroides.fragilis_0001.tif')])
print(CATEGORIES[prediction.argmax()])
print(prediction)


1/1 [==============================] - 0s 258ms/step
Propionibacterium_acnes
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]
