<a href="https://colab.research.google.com/github/Soni-20/BACTERIAL-IMAGE-CLASSIFICATION/blob/main/NewLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/MyDrive/

/content/drive/MyDrive


In [4]:
!ls

 adhaar.pdf
 BACT-PROJECT
'Colab Notebooks'
'Copy of *Your Name * - Product Analyst Assignment.gdoc'
 LSTM
 MAINDATASET
 mca134.gdoc
 mca134.html
 MINIPROJECT
 NewLSTM.ipynb
'nw photo.jpg'
 programing
'Prototyping presentation.gslides'
 REMAIN-BACT
 RESUME
'sij new.jpg'
'SONI ORIGINAL.pdf'
'SONI R resume(1) (1).pdf'
'SONI R resume(1).pdf'
'SONI R_TKM COLLEGE _MCA_TKM21MCA2036 (1).pdf'
'SONI R_TKM COLLEGE _MCA_TKM21MCA2036.pdf'
'Student infomation form.xlsx'
'Untitled form.gform'
'Untitled Jam.gjam'
'Untitled presentation.gslides'
'WEB LAB2.docx'
 X.pkl
 y.pkl


In [5]:
DIRECTORY = 'REMAIN-BACT/'

CATEGORIES = ['ACINETOBACTER'		 ,  'Lactobacillus.johnsonii',
'Bacteroides.fragilis'	   ,'Lactobacillus.paracasei',
'Bifidobacterium.spp',	   'Lactobacillus.plantarum',
'Candida.albicans'	 ,  'Lactobacillus.reuteri',
'Clostridium.perfringens'   , 'Micrococcus_spp',
'Enterococcus.faecalis'	,   'Neisseria_gonorrhoeae',
'Enterococcus.faecium'	  , 'Porfyromonas_gingivalis',
'Escherichia.coli'	,   'Propionibacterium_acnes',
'Fusobacterium'		  , 'Proteus',
'Lactobacillus.casei'	,   'Pseudomonas_aeruginosa',
'Lactobacillus.crispatus'   , 'Staphylococcus_aureus',
'Lactobacillus.delbrueckii' , 'Staphylococcus_epidermidis',
'Lactobacillus.gasseri'	  , 'Staphylococcus_saprophiticus',
'Lactobacillus.jehnsenii']

In [6]:
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])

In [7]:
data

[[array([[210, 210, 200, ..., 200, 182, 209],
         [210, 209, 210, ..., 176, 189, 193],
         [176, 210, 209, ..., 174, 177, 212],
         ...,
         [211, 212, 216, ..., 211, 211, 212],
         [211, 213, 213, ..., 210, 210, 211],
         [212, 211, 213, ..., 209, 211, 211]], dtype=uint8), 0],
 [array([[210, 210, 200, ..., 200, 182, 209],
         [210, 209, 210, ..., 176, 189, 193],
         [176, 210, 209, ..., 174, 177, 212],
         ...,
         [211, 212, 216, ..., 211, 211, 212],
         [211, 213, 213, ..., 210, 210, 211],
         [212, 211, 213, ..., 209, 211, 211]], dtype=uint8), 0],
 [array([[209, 178, 208, ..., 206, 208, 207],
         [208, 202, 201, ..., 208, 207, 209],
         [171, 202, 208, ..., 208, 206, 208],
         ...,
         [151, 146, 156, ..., 198, 185, 184],
         [178, 182, 175, ..., 175, 178, 199],
         [174, 181, 191, ..., 188, 212, 165]], dtype=uint8), 0],
 [array([[210, 209, 210, ..., 166, 210, 200],
         [211, 210, 210, ..

In [8]:
data[0][1]

0

In [9]:
import random

random.shuffle(data)

In [10]:
X = []
y = []

In [11]:
for features, label in data:
    X.append(features)
    y.append(label)

In [12]:
X = np.array(X)
y = np.array(y)

In [13]:
X

array([[[163, 218, 176, ..., 219, 220, 219],
        [192, 174, 216, ..., 218, 219, 212],
        [210, 210, 132, ..., 196, 214, 218],
        ...,
        [216, 219, 209, ..., 220, 206, 219],
        [220, 220, 219, ..., 186, 219, 218],
        [219, 217, 218, ..., 218, 219, 219]],

       [[213, 215, 213, ..., 214, 216, 214],
        [214, 216, 214, ..., 214, 213, 215],
        [214, 214, 215, ..., 213, 214, 215],
        ...,
        [216, 216, 216, ..., 219, 216, 207],
        [216, 217, 217, ..., 210, 218, 201],
        [216, 216, 216, ..., 209, 209, 216]],

       [[214, 213, 213, ..., 206, 174, 201],
        [211, 213, 213, ..., 187, 197, 204],
        [213, 213, 213, ..., 204, 205, 206],
        ...,
        [182, 190, 196, ..., 210, 210, 208],
        [170, 187, 198, ..., 198, 206, 205],
        [192, 196, 189, ..., 205, 205, 170]],

       ...,

       [[211, 206, 202, ..., 209, 207, 202],
        [199, 205, 199, ..., 208, 201, 210],
        [210, 210, 206, ..., 203, 199, 208

In [14]:
y

array([26, 16,  4, 24,  6,  6, 22, 16,  2, 10, 20, 22, 25,  1, 24,  5,  4,
        5,  0,  6,  1, 16,  2,  3,  5,  4,  9, 10,  5,  0, 20,  9,  7,  1,
        8,  8, 12,  1,  5, 24,  0, 11,  1,  8, 21,  4,  0,  1, 11,  2, 22,
       10,  9,  2, 13,  7, 24, 16, 14, 24, 16, 26, 10, 10, 10,  0,  3, 24,
        8,  2, 22, 24, 16, 12, 18, 25,  8, 18, 20, 16,  1, 26,  1,  2,  7,
        5, 20,  7, 10, 20, 20, 11, 17,  8,  4, 14, 18, 12, 26,  3,  0,  5,
       18,  0, 26, 14, 10,  5, 12,  3,  5,  5, 14,  0, 16, 12, 24, 22,  6,
       26, 15, 15,  6, 26, 26,  0,  8,  2,  1, 18, 16, 10, 10, 26, 12, 14,
       16,  4,  0, 24, 14,  8, 10, 22,  3, 20, 13,  0,  3,  0, 18, 12,  3,
       10, 18,  4,  4,  0, 20, 20, 20, 12, 10,  2,  0, 24, 18, 24,  7, 12,
       10,  3,  7,  0, 20,  4, 12, 16, 23,  4,  0, 22,  4,  3,  4,  3,  7,
        5,  8,  2,  3,  1, 23, 12,  8,  6, 24,  8, 18, 10, 13, 18, 18,  3,
       26,  5,  2, 20,  0, 22, 14,  5,  2, 18,  0,  3,  6, 22,  4, 12,  1,
       22, 18,  1,  1, 26

In [15]:
import pickle

In [16]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))

In [17]:

X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [18]:
X

array([[[163, 218, 176, ..., 219, 220, 219],
        [192, 174, 216, ..., 218, 219, 212],
        [210, 210, 132, ..., 196, 214, 218],
        ...,
        [216, 219, 209, ..., 220, 206, 219],
        [220, 220, 219, ..., 186, 219, 218],
        [219, 217, 218, ..., 218, 219, 219]],

       [[213, 215, 213, ..., 214, 216, 214],
        [214, 216, 214, ..., 214, 213, 215],
        [214, 214, 215, ..., 213, 214, 215],
        ...,
        [216, 216, 216, ..., 219, 216, 207],
        [216, 217, 217, ..., 210, 218, 201],
        [216, 216, 216, ..., 209, 209, 216]],

       [[214, 213, 213, ..., 206, 174, 201],
        [211, 213, 213, ..., 187, 197, 204],
        [213, 213, 213, ..., 204, 205, 206],
        ...,
        [182, 190, 196, ..., 210, 210, 208],
        [170, 187, 198, ..., 198, 206, 205],
        [192, 196, 189, ..., 205, 205, 170]],

       ...,

       [[211, 206, 202, ..., 209, 207, 202],
        [199, 205, 199, ..., 208, 201, 210],
        [210, 210, 206, ..., 203, 199, 208

In [19]:
y

array([26, 16,  4, 24,  6,  6, 22, 16,  2, 10, 20, 22, 25,  1, 24,  5,  4,
        5,  0,  6,  1, 16,  2,  3,  5,  4,  9, 10,  5,  0, 20,  9,  7,  1,
        8,  8, 12,  1,  5, 24,  0, 11,  1,  8, 21,  4,  0,  1, 11,  2, 22,
       10,  9,  2, 13,  7, 24, 16, 14, 24, 16, 26, 10, 10, 10,  0,  3, 24,
        8,  2, 22, 24, 16, 12, 18, 25,  8, 18, 20, 16,  1, 26,  1,  2,  7,
        5, 20,  7, 10, 20, 20, 11, 17,  8,  4, 14, 18, 12, 26,  3,  0,  5,
       18,  0, 26, 14, 10,  5, 12,  3,  5,  5, 14,  0, 16, 12, 24, 22,  6,
       26, 15, 15,  6, 26, 26,  0,  8,  2,  1, 18, 16, 10, 10, 26, 12, 14,
       16,  4,  0, 24, 14,  8, 10, 22,  3, 20, 13,  0,  3,  0, 18, 12,  3,
       10, 18,  4,  4,  0, 20, 20, 20, 12, 10,  2,  0, 24, 18, 24,  7, 12,
       10,  3,  7,  0, 20,  4, 12, 16, 23,  4,  0, 22,  4,  3,  4,  3,  7,
        5,  8,  2,  3,  1, 23, 12,  8,  6, 24,  8, 18, 10, 13, 18, 18,  3,
       26,  5,  2, 20,  0, 22, 14,  5,  2, 18,  0,  3,  6, 22,  4, 12,  1,
       22, 18,  1,  1, 26

In [20]:
X = X/255
X

X = X.reshape(-1, 60, 60, 1)


In [21]:

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten


In [22]:
from keras.layers import LSTM

In [24]:
model = Sequential()
model.add(LSTM(30,activation='relu',kernel_initializer='he_uniform',input_shape=(60,60)))
model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(27, activation = 'softmax'))


In [25]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [26]:

model.fit(X, y, epochs=1008, validation_split=0.1)

Epoch 1/1008
12/12 [==============================] - 3s 58ms/step - loss: 3.3485 - accuracy: 0.0495 - val_loss: 3.2580 - val_accuracy: 0.0465
Epoch 2/1008
12/12 [==============================] - 0s 26ms/step - loss: 3.1624 - accuracy: 0.0599 - val_loss: 3.2217 - val_accuracy: 0.0698
Epoch 3/1008
12/12 [==============================] - 0s 26ms/step - loss: 3.0899 - accuracy: 0.0990 - val_loss: 3.2304 - val_accuracy: 0.0698
Epoch 4/1008
12/12 [==============================] - 0s 27ms/step - loss: 3.0182 - accuracy: 0.1276 - val_loss: 3.2264 - val_accuracy: 0.0930
Epoch 5/1008
12/12 [==============================] - 0s 27ms/step - loss: 2.9824 - accuracy: 0.1276 - val_loss: 3.1408 - val_accuracy: 0.1163
Epoch 6/1008
12/12 [==============================] - 0s 25ms/step - loss: 2.9018 - accuracy: 0.1432 - val_loss: 3.0365 - val_accuracy: 0.0930
Epoch 7/1008
12/12 [==============================] - 0s 25ms/step - loss: 2.9734 - accuracy: 0.1146 - val_loss: 3.1229 - val_accuracy: 0.0465